import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Audio from "../widgets/audio/Audio";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <div>我是关于页面</div>
        <Link href={"/"}>链接到首页</Link>
        <Audio></Audio>
      </div>
    </div>
  );
};

export default Home;
