import React, { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import Tet from "../contents/langs/cpp/cpp_cheat/cpp_cheat.mdx";

const Home: NextPage = () => {
  useEffect(() => {
    import("/src/elements/code");
    import("/src/elements/math");
  }, []);

  return (
    <div>
      <Head>
        <title>我的笔记</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"book-page article heti heti--sans"}>
        <Tet></Tet>
      </div>
      <Link href={"/about"}>关于 </Link>
    </div>
  );
};

export default Home;
