import type { NextPage } from "next";
import Head from "next/head";
import Menu from "../components/menu/Menu";
import createNavs from "../header_navs";
import { useEffect, useLayoutEffect, useState } from "react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ padding: 40 }}>
          <Menu navs={createNavs()[0].children} />
        </div>
      </main>
    </div>
  );
};

export default Home